name = input("What is your name? ")
print(f"Hello, {name}!")
print(name.capitalize())
print(name.upper())
print(name.lower())
print(len(name))
print(name[0])
print(name[0:6])
print(name[0:6:2])
print(name[::-1])